name: Build and Test Mobile App

on:
  push:
    branches:
      - 'version-*'
  pull_request:
    branches:
      - 'version-*' 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install app dependencies
      run: |
        cd mobile
        yarn install

    - name: Build app
      run: |
        cd mobile
        yarn build:android

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: mobile/android/app/build/outputs/apk/release/app-release.apk
