name: Deploy
on:
  push:
    branches: version-1.0.x
  pull_request:
    branches: version-1.0.x

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Build step
        run: "cd server && npm install && npm run build" # 📝 Update the build command(s) if necessary

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "flat-badger-42"
          entrypoint: "./index.ts" # 📝 Update the entrypoint if necessary
          root: "./server" # 📝 Update the root if necessary
