name: Lint

on:
  push:
    branches:
      - 'version-*' # Only run on version branches
  pull_request:
    branches:
      - 'version-*' # Only run on version branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Adjust the Node.js version as needed

      - name: Install dependencies
        run: |
          cd server
          npm ci

      - name: Lint
        run: |
          cd server
          npm run lint
